"""Constants for FirstView integration."""

DOMAIN = "firstview"

CONF_EMAIL = "email"
CONF_PASSWORD = "password"
CONF_AM_ENABLED = "am_enabled"
CONF_AM_START = "am_start"
CONF_AM_END = "am_end"
CONF_PM_ENABLED = "pm_enabled"
CONF_PM_START = "pm_start"
CONF_PM_END = "pm_end"
CONF_DAY_M = "day_m"
CONF_DAY_T = "day_t"
CONF_DAY_W = "day_w"
CONF_DAY_R = "day_r"
CONF_DAY_F = "day_f"
CONF_DAY_SA = "day_sa"
CONF_DAY_SU = "day_su"
CONF_PRESET = "preset"
CONF_DAILY_INTERVAL_HOURS = "daily_interval_hours"
CONF_HOURLY_INTERVAL_MINUTES = "hourly_interval_minutes"

DEFAULT_AM_ENABLED = True
DEFAULT_AM_START = "06:00"
DEFAULT_AM_END = "08:00"
DEFAULT_PM_ENABLED = True
DEFAULT_PM_START = "13:00"
DEFAULT_PM_END = "15:00"
DEFAULT_DAY_M = True
DEFAULT_DAY_T = True
DEFAULT_DAY_W = True
DEFAULT_DAY_R = True
DEFAULT_DAY_F = True
DEFAULT_DAY_SA = False
DEFAULT_DAY_SU = False
DEFAULT_PRESET = "custom"
DEFAULT_DAILY_INTERVAL_HOURS = 24
DEFAULT_HOURLY_INTERVAL_MINUTES = 60

MAX_WINDOW_MINUTES = 120
MIN_DAILY_INTERVAL_HOURS = 6
MAX_DAILY_INTERVAL_HOURS = 48
MIN_HOURLY_INTERVAL_MINUTES = 5
MAX_HOURLY_INTERVAL_MINUTES = 180

PRESET_CUSTOM = "custom"
PRESET_SCHOOL_DEFAULT = "school_default"

WS_BACKOFF_MIN_SECONDS = 1
WS_BACKOFF_MAX_SECONDS = 90
WS_WINDOW_SLEEP_SECONDS = 15
AUTH_BACKOFF_BASE_SECONDS = 1
AUTH_BACKOFF_MAX_SECONDS = 30
AUTH_RETRIES = 3
DELETE_CONFIRM_WINDOW_SECONDS = 10

COGNITO_USER_POOL_ID = "us-east-1_rGFbOE8vH"
COGNITO_CLIENT_ID = "7n0v07n3eja2au8qhkbbnc009r"
COGNITO_REGION = "us-east-1"

DASHBOARD_BASE = "https://dashboard.myfirstview.com"
WS_BASE = "wss://wbsckt.myfirstview.com"

PLATFORMS = ["sensor", "device_tracker"]
